import Head from 'next/head'
import { SecExperiences } from '@/components/SecExperiences';
import { SecSkillset } from '@/components/SecSkillset';
import { Footer } from '@/components/Footer';
import { Header } from '@/components/Header';

// Inspired by
// https://webflow.com/made-in-webflow/website/Portfolio-Website-Free-Template

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Header />
          <SecSkillset />
          <SecExperiences />
          <Footer />
      </main>
    </>
  )
}
